column:
  lake_game:
    - game_id
    - game_date
    - game_start_time
    - game_time
    - game_series
    - game_status
    - game_result
    - team_top_id
    - team_top_name
    - team_bottom_id
    - team_bottom_name
    - score_top
    - score_bottom
    - hit_top
    - hit_bottom
    - error_top
    - error_bottom
    - picher_win_id
    - picher_lose_id
    - picher_save_id
    - starting_picher_bottom_id
    - starting_picher_top_id
    - audience_num
    - umpire_plate
    - umpire_first
    - umpire_second
    - umpire_third
    - exec_datetime
  
  lake_score:
    - game_id
    - index
    - inning
    - top_buttom
    - result_main
    - result_sub
    - batter_id
    - batter_side
    - pitcher_id
    - pitcher_side
    - base_1
    - base_2
    - base_3
    - exec_datetime
  
  lake_player:
    - player_id
    - player_name
    - player_name_kana
    - number
    - birth_day
    - birth_place
    - height
    - weight
    - blood_type
    - throw_batting
    - draft_year
    - pro_age
    - keireki
    - profile_text
    - img_url
    - exec_datetime
