name: 巨人
  id: 1
  full_name: 読売ジャイアンツ
  league: セ・リーグ
name: 阪神
  id: 5
  full_name: 阪神タイガース
  league: セ・リーグ
name: 中日
  id: 4
  full_name: 中日ドラゴンズ
  league: セ・リーグ
name: 横浜
  id: 3
  full_name: 阪神タイガース
  league: セ・リーグ
name: 広島
  id: 6
  full_name: 広島東洋カープ
  league: セ・リーグ
name: ヤクルト
  id: 2
  full_name: 東京ヤクルトスワローズ
  league: セ・リーグ
name: ソフトバンク
  id: 12
  full_name: 福岡ソフトバンクホークス
  league: パ・リーグ
name: ロッテ
  id: 9
  full_name: 千葉ロッテマリーンズ
  league: パ・リーグ
name: 西武
  id: 7
  full_name: 西武ライオンズ
  league: パ・リーグ
name: 楽天
  id: 376
  full_name: 楽天ゴールデンイーグルス
  league: パ・リーグ
name: 日ハム
  id: 8
  full_name: 北海道日本ハムファイターズ
  league: パ・リーグ
name: オリックス
  id: 11
  full_name: オリックス・バファローズ
  league: パ・リーグ