table:
  lake_game:
    db_name:
      sponavi_lake
    table_name:
      game
    column:
      - name: game_id
        type: STRING
      - name: game_date
        type: DATE
      - name: game_start_time
        type: STRING
      - name: game_title
        type: STRING
      - name: game_time
        type: STRING
      - name: game_series
        type: STRING
      - name: game_status
        type: STRING
      - name: game_result
        type: STRING
      - name: team_top_id
        type: STRING
      - name: team_top_name
        type: STRING
      - name: team_bottom_id
        type: STRING
      - name: team_bottom_name
        type: STRING
      - name: score_top
        type: INTEGER
      - name: score_bottom
        type: INTEGER
      - name: hit_top
        type: INTEGER
      - name: hit_bottom
        type: INTEGER
      - name: error_top
        type: INTEGER
      - name: error_bottom
        type: INTEGER
      - name: picher_win_id
        type: STRING
      - name: picher_lose_id
        type: STRING
      - name: picher_save_id
        type: STRING
      - name: starting_picher_bottom_id
        type: STRING
      - name: starting_picher_top_id
        type: STRING
      - name: audience_num
        type: STRING
      - name: umpire_plate
        type: STRING
      - name: umpire_first
        type: STRING
      - name: umpire_second
        type: STRING
      - name: umpire_third
        type: STRING
      - name: flow_id
        type: STRING

  lake_score:
    db_name:
      sponavi_lake
    table_name:
      score
    column:
      - name: game_id
        type: STRING
      - name: index
        type: STRING
      - name: inning
        type: STRING
      - name: top_buttom
        type: STRING
      - name: result_main
        type: STRING
      - name: result_sub
        type: STRING
      - name: dakyu
        type: STRING
      - name: batter_id
        type: STRING
      - name: batter_side
        type: STRING
      - name: pitcher_id
        type: STRING
      - name: pitcher_side
        type: STRING
      - name: base_1
        type: STRING
      - name: base_2
        type: STRING
      - name: base_3
        type: STRING
      - name: exec_datetime
        type: DATETIME

  lake_ball:
    db_name:
      sponavi_lake
    table_name:
      ball
    column:
      - name: game_id
        type: STRING
      - name: index
        type: STRING
      - name: number
        type: INTEGER
      - name: balltype
        type: STRING
      - name: speed
        type: NUMERIC
      - name: result
        type: STRING
      - name: position_top
        type: NUMERIC
      - name: position_left
        type: NUMERIC
      - name: exec_datetime
        type: DATETIME

  lake_player:
    db_name:
      sponavi_lake
    table_name:
      player
    column:
      - name: player_id
        type: STRING
      - name: player_name
        type: STRING
      - name: player_name_kana
        type: STRING
      - name: team_full_name
        type: STRING
      - name: number
        type: STRING
      - name: birth_day
        type: DATE
      - name: birth_place
        type: STRING
      - name: height
        type: INTEGER
      - name: weight
        type: INTEGER
      - name: blood_type
        type: STRING
      - name: throw_batting
        type: STRING
      - name: draft_year
        type: STRING
      - name: pro_age
        type: INTEGER
      - name: keireki
        type: STRING
      - name: profile_text
        type: STRING
      - name: img_url
        type: STRING
      - name: flow_id
        type: STRING

  dm_team:
    db_name:
      sponavi_dm
    table_name:
      team
    column:
      - name: team_id
        type: STRING
      - name: team_name
        type: STRING
      - name: team_name_full
        type: STRING
      - name: league
        type: STRING