team:
  巨人: 
    id: 1
    full_name: 読売ジャイアンツ
    league: セ・リーグ
  阪神: 
    id: 5
    full_name: 阪神タイガース
    league: セ・リーグ
  中日: 
    id: 4
    full_name: 中日ドラゴンズ
    league: セ・リーグ
  横浜: 
    id: 3
    full_name: 阪神タイガース
    league: セ・リーグ
  広島: 
    id: 6
    full_name: 広島東洋カープ
    league: セ・リーグ
  ヤクルト: 
    id: 2
    full_name: 東京ヤクルトスワローズ
    league: セ・リーグ
  ソフトバンク: 
    id: 12
    full_name: 福岡ソフトバンクホークス
    league: パ・リーグ
  ロッテ: 
    id: 9
    full_name: 千葉ロッテマリーンズ
    league: パ・リーグ
  西武: 
    id: 7
    full_name: 西武ライオンズ
    league: パ・リーグ
  楽天: 
    id: 376
    full_name: 楽天ゴールデンイーグルス
    league: パ・リーグ
  日ハム: 
    id: 8
    full_name: 北海道日本ハムファイターズ
    league: パ・リーグ
  オリックス: 
    id: 11
    full_name: オリックス・バファローズ
    league: パ・リーグ

team_central_league:
  - 巨人
  - 横浜
  - 中日
  - 阪神
  - 広島
  - ヤクルト

team_pacific_league:
  - ソフトバンク
  - ロッテ
  - 西武
  - 楽天
  - 日ハム
  - オリックス
